//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.FullStack.F2X.Recaudos.Datos.ORM
{
    using System;
    
    public partial class RecaudosList
    {
        public string Estacion { get; set; }
        public string Sentido { get; set; }
        public int Hora { get; set; }
        public string Categoria { get; set; }
        public int Cantidad { get; set; }
        public decimal ValorTabulado { get; set; }
        public System.DateTime FechaConsulta { get; set; }
    }
}
