//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.FullStack.F2X.Recaudos.Datos.ORM
{
    using System;
    
    public partial class ReporteValorTabulado
    {
        public System.DateTime FechaConsulta { get; set; }
        public string Estacion { get; set; }
        public Nullable<int> TotalCantidad { get; set; }
        public Nullable<decimal> TotalValor { get; set; }
    }
}
